# Generated by Django 4.0.6 on 2022-12-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_image_remove_movie_price_movie_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(null=True, upload_to='videos', verbose_name=''),
        ),
    ]
